import {
    autoGeneratedHashKey,
    rangeKey,
    table,
    attribute
} from '@aws/dynamodb-data-mapper-annotations';
// Guide about AWS DynamoDB data mapper https://aws.amazon.com/ru/blogs/developer/introducing-the-amazon-dynamodb-datamapper-for-javascript-developer-preview/

@table(process.env.DYNAMODB_TABLE)
export class Todo {
    @autoGeneratedHashKey()
    id: string;

    @rangeKey()
    createdAt: Date;

    @rangeKey()
    updatedAt: Date;

    // payload

    @attribute()
    text: string;

    @attribute()
    checked: boolean;
}